export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <h2>header</h2>
        <p>共通の項目が表示されるらしい</p>
        <p>むずいよ～～～～～</p>
        <button>助けて</button>

        {children}
      </body>
    </html>
  );
}
