export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        {/* <h2>タイトル１です！</h2>
        <p>共通の項目が表示されるらしい</p>
        <h2>タイトル２です！</h2>
        <p>共通の項目が表示されるらしい</p>
        <h2>タイトルです！</h2>
        <p>共通の項目が表示されるらしい</p> */}

        {children}
      </body>
    </html>
  );
}
